export const buttons = [
  {
    title: "AC",
    backgroundColor: "#A5A5A5",
    color: "#000000",
    value: "delete-all",
  },
  {
    title: "+/-",
    backgroundColor: "#A5A5A5",
    color: "#000000",
    value: "invert",
  },
  {
    title: "%",
    backgroundColor: "#A5A5A5",
    color: "#000000",
    value: "percent",
  },
  {
    title: "/",
    backgroundColor: "#FF9F0A",
    color: "#FFFFFF",
    value: "divide",
  },
  {
    title: "7",
    backgroundColor: "#333333",
    color: "#FFFFFF",
    value: "7",
  },
  {
    title: "8",
    backgroundColor: "#333333",
    color: "#FFFFFF",
    value: "8",
  },
  {
    title: "9",
    backgroundColor: "#333333",
    color: "#FFFFFF",
    value: "9",
  },
  {
    title: "X",
    backgroundColor: "#FF9F0A",
    color: "#FFFFFF",
    value: "multiply",
  },
  {
    title: "4",
    backgroundColor: "#333333",
    color: "#FFFFFF",
    value: "4",
  },
  {
    title: "5",
    backgroundColor: "#333333",
    color: "#FFFFFF",
    value: "5",
  },
  {
    title: "6",
    backgroundColor: "#333333",
    color: "#FFFFFF",
    value: "6",
  },
  {
    title: "-",
    backgroundColor: "#FF9F0A",
    color: "#FFFFFF",
    value: "subtract",
  },
  {
    title: "1",
    backgroundColor: "#333333",
    color: "#FFFFFF",
    value: "1",
  },
  {
    title: "2",
    backgroundColor: "#333333",
    color: "#FFFFFF",
    value: "2",
  },
  {
    title: "3",
    backgroundColor: "#333333",
    color: "#FFFFFF",
    value: "3",
  },
  {
    title: "+",
    backgroundColor: "#FF9F0A",
    color: "#FFFFFF",
    value: "add",
  },
  {
    title: "0",
    backgroundColor: "#333333",
    color: "#FFFFFF",
    value: "0",
  },
  {
    title: ",",
    backgroundColor: "#333333",
    color: "#FFFFFF",
    value: ",",
  },
  {
    title: "=",
    backgroundColor: "#FF9F0A",
    color: "#FFFFFF",
    value: "equals",
  },
];
